# Pipeline para sincronizar Azure Repos com GitHub
trigger:
- main  # ou master, dependendo da sua branch principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- task: PowerShell@2
  displayName: 'Sync to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      # Configurar usuário Git
      git config --global user.email "ikee.bittin@gmail.com"
      git config --global user.name "Caike Bittin"
      
      # Adicionar remote do GitHub (substitua pela URL do seu repo)
      git remote add github https://$(GITHUB_TOKEN)@github.com/caikebittin/BookingSystem.git
      
      # Fazer push para GitHub
      git push github HEAD:master --force
  env:
    GITHUB_TOKEN: $(GITHUB_PAT)