trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- task: Bash@3
  displayName: 'Sync to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "ikee.bittin@gmail.com"
      git config --global user.name "Caike Bittin"
      
      # Remove remote se existir
      git remote remove github 2>/dev/null || true
      
      # Adiciona remote
      git remote add github https://$(GITHUB_PAT)@github.com/caikebittin/BookingSystem.git
      
      # Primeiro push com --set-upstream para criar a branch
      git push --set-upstream github master